# Generated by Django 5.0.1 on 2024-06-29 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0011_followupvisit_user_patientdata_user_services_user_and_more'),
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalpathologyresult',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chempath_result_payment', to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='generaltestresult',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_result_payment', to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='microbiologyresult',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_result_payment', to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='serologyresult',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serology_result_payment', to='ehr.paypoint'),
        ),
    ]
