# Generated by Django 5.0.1 on 2024-05-13 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0016_alter_vitalsigns_options'),
        ('pathology', '0002_serologyresult_delete_serologytestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematologytest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.services'),
        ),
    ]
