# Generated by Django 5.0.1 on 2024-06-30 00:17

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_chemicalpathologyresult_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalpathologyresult',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generaltestresult',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microbiologyresult',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serologyresult',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chemicalpathologyresult',
            name='result',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generaltestresult',
            name='result',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microbiologyresult',
            name='result',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serologyresult',
            name='result',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
