# Generated by Django 5.0.1 on 2024-05-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0014_remove_paypoint_hematology_result_and_more'),
        ('pathology', '0002_alter_hematologyresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematologyresult',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
    ]
