# Generated by Django 5.0.1 on 2024-06-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_chemicalpathologyresult_cleared_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SerologyTestName',
            new_name='ChempathTest',
        ),
        migrations.RenameModel(
            old_name='ChempathTestName',
            new_name='SerologyTest',
        ),
        migrations.RemoveField(
            model_name='generaltestresult',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='microbiologyresult',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='serologyresult',
            name='unit',
        ),
    ]
