# Generated by Django 5.0.1 on 2024-05-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_hematologytest_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hematologytest',
            name='service',
        ),
        migrations.AddField(
            model_name='hematologytest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
