# Generated by Django 5.0.1 on 2024-05-15 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0015_alter_paypoint_service'),
        ('pathology', '0003_hematologyresult_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematologyresult',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hematology_result_payment', to='ehr.paypoint'),
        ),
    ]
