# Generated by Django 5.0.1 on 2024-05-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0004_alter_hematologyresult_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematologyresult',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
