# Generated by Django 5.0.1 on 2024-07-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0004_rename_serologytestname_chempathtest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalpathologyresult',
            name='test',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pathology.chempathtest'),
        ),
        migrations.AlterField(
            model_name='serologyresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pathology.serologytest'),
        ),
        migrations.DeleteModel(
            name='GeneralTestResult',
        ),
    ]
