# Generated by Django 5.0.1 on 2024-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0005_hematologyresult_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='chempathtestname',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generaltestresult',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='microbiologytest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serologytestname',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
