# Generated by Django 5.0.1 on 2024-06-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0006_chempathtestname_price_generaltestresult_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematologytest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
