# Generated by Django 5.0.1 on 2024-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0007_hematologytest_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematologyresult',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
