# Generated by Django 4.2.7 on 2023-11-06 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_item_cost_alter_item_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_issued_to', models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('ACCOUNT', 'ACCOUNT'), ('BIO-MEDICAL ENGINEERING', 'BIO-MEDICAL ENGINEERING'), ('CATERING', 'CATERING'), ('CLINICAL SERVICES', 'CLINICAL SERVICES'), ('ENGINEERING', 'ENGINEERING'), ('INTERNAL AUDIT', 'INTERNAL AUDIT'), ('LAUNDRY', 'LAUNDRY'), ('LEGAL', 'LEGAL'), ('MEDICAL RECORD', 'MEDICAL RECORD'), ('MEDICAL ILLUSTRATION', 'MEDICAL ILLUSTRATION'), ('NURSING EDUCATION', 'NURSING EDUCATION'), ('NURSING SERVICES', 'NURSING SERVICES'), ('PATHOLOGY', 'PATHOLOGY'), ('PHARMACY', 'PHARMACY'), ('PHYSIOTHERAPHY', 'PHYSIOTHERAPHY'), ('PROSTHETIC AND OTHOTICS', 'PROSTHETIC AND OTHOTICS'), ('PROCUMENT', 'PROCUMENT'), ('PUBLIC HEALTH', 'PUBLIC HEALTH'), ('OCCUPATIONAL THERAPHY', 'OCCUPATIONAL THERAPHY'), ('RADIOLOGY', 'RADIOLOGY'), ('SERVICOM', 'SERVICOM'), ('SOCIAL WELFARE', 'SOCIAL WELFARE'), ('STORE', 'STORE'), ('TELEPHONE', 'TELEPHONE'), ('TRANSPORT', 'TRANSPORT')], max_length=100, null=True)),
                ('quantity_issued', models.IntegerField()),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('issued_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='issueditem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='issueditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemquantitylog',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='department',
        ),
        migrations.RemoveField(
            model_name='item',
            name='timestamp_issued',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_issued',
        ),
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='IssuedItem',
        ),
        migrations.DeleteModel(
            name='ItemQuantityLog',
        ),
        migrations.AddField(
            model_name='issued_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
