# Generated by Django 4.2.7 on 2023-11-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_issued_item_remove_issueditem_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_item',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
