# Generated by Django 4.2.7 on 2023-11-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_issued_item_date_issued_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issued_item',
            options={'verbose_name_plural': 'item issued record'},
        ),
    ]
