# Generated by Django 4.2.7 on 2023-11-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_issued_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issued_item',
            options={'verbose_name_plural': 'item issue record'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'list of items'},
        ),
    ]
