# Generated by Django 4.2.7 on 2023-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_issued_item_options_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
