# Generated by Django 4.2.7 on 2023-11-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_record_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name_plural': 'records'},
        ),
        migrations.AlterField(
            model_name='record',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.item'),
        ),
    ]
