# Generated by Django 4.2.7 on 2023-11-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_record_options_alter_record_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='balance',
        ),
        migrations.AddField(
            model_name='record',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
