# Generated by Django 4.2.7 on 2023-11-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_item_balance_record_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='balance',
        ),
        migrations.AddField(
            model_name='item',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
