# Generated by Django 4.2.7 on 2023-11-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_record_balance_item_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
