# Generated by Django 4.2.7 on 2023-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_record_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_purchased', models.PositiveIntegerField(default=0)),
                ('total_issued', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
