# Generated by Django 4.2.7 on 2023-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_inventory_total_issued_issuance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
