# Generated by Django 4.2.7 on 2023-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_issuance_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
