# Generated by Django 4.2.7 on 2023-11-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
