# Generated by Django 4.2.7 on 2023-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_issuance_inventory_remove_item_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
