# Generated by Django 4.2.7 on 2023-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_record_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
