# Generated by Django 4.2.7 on 2023-11-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_item_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='balance',
        ),
    ]
