# Generated by Django 4.2.7 on 2023-11-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_item_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
