# Generated by Django 4.2.7 on 2023-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_itemhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ItemHistory',
        ),
    ]
