# Generated by Django 4.2.7 on 2023-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_item_updated_at_delete_itemhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_value',
        ),
        migrations.AddField(
            model_name='item',
            name='total_purchased_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
