# Generated by Django 4.2.7 on 2023-11-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_remove_item_total_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_purchased_quantity',
        ),
    ]
