# Generated by Django 4.2.7 on 2023-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_item_total_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
