# Generated by Django 4.2.7 on 2023-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
    ]
