# Generated by Django 4.2.7 on 2023-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_record_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
