# Generated by Django 4.2.7 on 2023-11-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_record_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'purchases record'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name_plural': 'items issued record'},
        ),
        migrations.AddField(
            model_name='record',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.unit'),
        ),
    ]
