# Generated by Django 4.2.7 on 2023-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_item_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cost',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
