# Generated by Django 4.2.7 on 2023-12-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_rename_cost_item_unit_price_purchase_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.PositiveIntegerField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restock_items', to='inventory.unit')),
            ],
            options={
                'verbose_name_plural': 'restocking record',
            },
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
