# Generated by Django 4.2.7 on 2024-01-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_item_invoice_number_item_store_receiving_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restock',
            name='store_receiving_voucher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
