# Generated by Django 4.2.7 on 2024-01-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_restock_invoice_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='department_issued_to',
            new_name='issued_to',
        ),
        migrations.RemoveField(
            model_name='item',
            name='issued_to',
        ),
    ]
