# Generated by Django 4.2.7 on 2024-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_record_issued_to_alter_record_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
