# Generated by Django 5.0.1 on 2024-10-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_alter_record_issued_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='total_purchased_quantity',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='store_receiving_voucher',
        ),
        migrations.RemoveField(
            model_name='record',
            name='requisition_number',
        ),
        migrations.RemoveField(
            model_name='record',
            name='siv',
        ),
        migrations.AlterField(
            model_name='record',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
    ]
