# Generated by Django 5.0.1 on 2024-05-14 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ehr', '0003_remove_clinicalnote_diagnosis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='CLASS OF DRUG')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='DATE DRUG WAS ADDED')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='DRUG NAME')),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='GENERIC NAME')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='BRAND NAME')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='SUPPLIER')),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOSAGE FORM')),
                ('pack_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PACK PRICE')),
                ('pack_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='PACK SIZE')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='COST PRICE')),
                ('total_purchased_quantity', models.PositiveIntegerField(default=0, verbose_name='TOTAL QTY PURCHASED')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='DATE ADDED')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='DATE UPDATED')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_drugs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pharm.category')),
            ],
            options={
                'verbose_name_plural': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='Dispensary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY TO DISPENSE')),
                ('balance', models.PositiveIntegerField(blank=True, null=True, verbose_name='CURRENT BALANCE')),
                ('dispense_date', models.DateField(auto_now_add=True, verbose_name='DISPENSE DATE')),
                ('remark', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='REMARKS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_dispense', to='pharm.category')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_dispense', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_payments', to='ehr.patientdata')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_dispense', to='pharm.drug')),
            ],
            options={
                'verbose_name_plural': 'dispensary record',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.drug')),
            ],
            options={
                'verbose_name_plural': 'purchases record',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_issued_to', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='PHARMACY UNIT ISSUED TO')),
                ('siv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SIV')),
                ('srv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SRV')),
                ('invoice_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='INVOICE NUMBER')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY ISSUED')),
                ('balance', models.PositiveIntegerField(blank=True, null=True, verbose_name='CURRENT BALANCE')),
                ('date_issued', models.DateField(auto_now_add=True, verbose_name='DATE DRUG WAS ISSUED')),
                ('remark', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='REMARKS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='pharm.category')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='pharm.drug')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'drugs issued record',
            },
        ),
    ]
