# Generated by Django 5.0.1 on 2024-09-10 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ehr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ANALGESICS', 'Analgesics'), ('ANESTHETICS', 'Anesthetics'), ('ANTIBIOTICS', 'Antibiotics'), ('ANTICOAGULANTS', 'Anticoagulants'), ('ANTICONVULSANTS', 'Anticonvulsants'), ('ANTIDEPRESSANTS', 'Antidepressants'), ('ANTIDIABETICS', 'Antidiabetics'), ('ANTIEMETICS', 'Antiemetics'), ('ANTIFUNGALS', 'Antifungals'), ('ANTIHISTAMINES', 'Antihistamines'), ('ANTIHYPERTENSIVES', 'Antihypertensives'), ('ANTI_INFLAMMATORIES', 'Anti-inflammatories'), ('ANTINEOPLASTICS', 'Antineoplastics'), ('ANTIPARASITICS', 'Antiparasitics'), ('ANTIPSYCHOTICS', 'Antipsychotics'), ('ANTIVIRALS', 'Antivirals'), ('BRONCHODILATORS', 'Bronchodilators'), ('CARDIOVASCULAR', 'Cardiovascular'), ('CNS_STIMULANTS', 'CNS Stimulants'), ('CORTICOSTEROIDS', 'Corticosteroids'), ('DERMATOLOGICALS', 'Dermatologicals'), ('DIURETICS', 'Diuretics'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('HORMONES', 'Hormones'), ('IMMUNOSUPPRESSANTS', 'Immunosuppressants'), ('LIPID_LOWERING', 'Lipid-lowering'), ('MUSCLE_RELAXANTS', 'Muscle Relaxants'), ('NSAIDS', 'NSAIDs'), ('OPIOIDS', 'Opioids'), ('OPHTHALMICS', 'Ophthalmics'), ('PSYCHOTROPICS', 'Psychotropics'), ('SEDATIVES_HYPNOTICS', 'Sedatives/Hypnotics'), ('THYROID_PREPARATIONS', 'Thyroid Preparations'), ('VACCINES', 'Vaccines'), ('VITAMINS_MINERALS', 'Vitamins and Minerals'), ('OTHER', 'Other')], max_length=200, verbose_name='CLASS OF DRUG')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='DATE DRUG WAS ADDED')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='DRUG NAME')),
                ('status', models.BooleanField(default=True)),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='GENERIC NAME')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='BRAND NAME')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='SUPPLIER')),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOSAGE FORM')),
                ('pack_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='PACK PRICE')),
                ('pack_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='PACK SIZE')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='COST PRICE')),
                ('total_purchased_quantity', models.PositiveIntegerField(default=0, verbose_name='TOTAL QTY PURCHASED')),
                ('total_issued', models.PositiveIntegerField(default=0, verbose_name='TOTAL QTY ISSUED')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='DATE ADDED')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_drugs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pharm.category')),
            ],
            options={
                'verbose_name_plural': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='Dispensary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY TO DISPENSE')),
                ('dispensed_date', models.DateTimeField(auto_now_add=True, verbose_name='DISPENSE DATE')),
                ('remark', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='REMARKS')),
                ('quantity_deducted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_drug_catgory', to='pharm.category')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_drugs', to='ehr.patientdata')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_drug', to='pharm.drug')),
            ],
            options={
                'verbose_name_plural': 'dispensary record',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dispensed', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='REMARKS')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drug_catgory', to='pharm.category')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drug', to='pharm.drug')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drugs', to='ehr.patientdata')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharm_payment', to='ehr.paypoint')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'prescription record',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.drug')),
            ],
            options={
                'verbose_name_plural': 'purchases record',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_issued_to', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='PHARMACY UNIT ISSUED TO')),
                ('siv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SIV')),
                ('srv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SRV')),
                ('invoice_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='INVOICE NUMBER')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY ISSUED')),
                ('date_issued', models.DateTimeField(auto_now_add=True, verbose_name='DATE DRUG WAS ISSUED')),
                ('remark', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='REMARKS')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='pharm.category')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='pharm.drug')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'drugs issued record',
            },
        ),
    ]
