# Generated by Django 5.0.1 on 2024-11-17 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('update', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispensaryLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dispensary Locker', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('update', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drug',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='pack_price',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='status',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='total_issued',
        ),
        migrations.AddField(
            model_name='drug',
            name='entered_expiry_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='STRENGTH'),
        ),
        migrations.AddField(
            model_name='drug',
            name='supply_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='trade_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TRADE NAME'),
        ),
        migrations.AddField(
            model_name='record',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REMARKS'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_category', to='pharm.category'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'TABLET'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP'), ('INJECTION', 'INJECTION'), ('INFUSION', 'INFUSION'), ('SUSPENSION', 'SUSPENSION'), ('SOLUTION', 'SOLUTION'), ('CONSUMABLE', 'CONSUMABLE'), ('POWDER', 'POWDER'), ('GRANULE', 'GRANULE'), ('PELLET', 'PELLET'), ('EMULSION', 'EMULSION'), ('TINCTURE', 'TINCTURE'), ('OINTMENT', 'OINMENT'), ('CREAM', 'CREAM'), ('GEL', 'GEL'), ('SUPPOSITORY', 'SUPPOSITORY'), ('INHALER', 'INHALER'), ('IMPLANT', 'IMPLANT'), ('LOZENGE', 'LOZENGEN'), ('SPRAY', 'SPRAY'), ('TRANSDERMAL PATCH', 'TRANSDERMAL PATCH')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='REMARKS'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='REMARKS'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY ISSUED')),
                ('patient_info', models.CharField(max_length=100, null=True)),
                ('dispense_date', models.DateTimeField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_category', to='pharm.category')),
                ('dispensary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuing_dispensary', to='pharm.dispensarylocker')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_drugs', to='pharm.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restock_category', to='pharm.category')),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.drug')),
                ('restocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_restocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'restocking record',
            },
        ),
        migrations.CreateModel(
            name='ReturnedDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_info', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_category', to='pharm.category')),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.drug')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_returning', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_drugs', to='pharm.unit')),
            ],
            options={
                'verbose_name_plural': 'returned drugs record',
            },
        ),
        migrations.AddField(
            model_name='dispensarylocker',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_locker', to='pharm.unit'),
        ),
        migrations.AlterField(
            model_name='record',
            name='unit_issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.unit'),
        ),
        migrations.CreateModel(
            name='UnitIssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitissue_category', to='pharm.category')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_drugs', to='pharm.drug')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_unit', to='pharm.unit')),
                ('issued_to_locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.dispensarylocker')),
                ('moved_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_moved', to='pharm.box')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuing_unit', to='pharm.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity Available')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_store_drugs', to='pharm.drug')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_store', to='pharm.unit')),
            ],
        ),
        migrations.CreateModel(
            name='LockerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.drug')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharm.dispensarylocker')),
            ],
            options={
                'unique_together': {('locker', 'drug')},
            },
        ),
    ]
