# Generated by Django 5.0.1 on 2024-10-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dose',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='dosage'),
        ),
    ]
