# Generated by Django 5.0.1 on 2024-05-14 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_alter_prescription_patient'),
        ('pharm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensary',
            old_name='dispense_date',
            new_name='dispensed_date',
        ),
        migrations.RemoveField(
            model_name='dispensary',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='dispensary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dispensary',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_drug_catgory', to='pharm.category'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_drug', to='pharm.drug'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_dispensed', to='ehr.patientdata'),
        ),
    ]
