# Generated by Django 5.0.1 on 2024-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ANALGESICS', 'Analgesics'), ('ANESTHETICS', 'Anesthetics'), ('ANTIBIOTICS', 'Antibiotics'), ('ANTICOAGULANTS', 'Anticoagulants'), ('ANTICONVULSANTS', 'Anticonvulsants'), ('ANTIDEPRESSANTS', 'Antidepressants'), ('ANTIDIABETICS', 'Antidiabetics'), ('ANTIEMETICS', 'Antiemetics'), ('ANTIFUNGALS', 'Antifungals'), ('ANTIHISTAMINES', 'Antihistamines'), ('ANTIHYPERTENSIVES', 'Antihypertensives'), ('ANTI_INFLAMMATORIES', 'Anti-inflammatories'), ('ANTINEOPLASTICS', 'Antineoplastics'), ('ANTIPARASITICS', 'Antiparasitics'), ('ANTIPSYCHOTICS', 'Antipsychotics'), ('ANTIVIRALS', 'Antivirals'), ('BRONCHODILATORS', 'Bronchodilators'), ('CARDIOVASCULAR', 'Cardiovascular'), ('CNS_STIMULANTS', 'CNS Stimulants'), ('CORTICOSTEROIDS', 'Corticosteroids'), ('DERMATOLOGICALS', 'Dermatologicals'), ('DIURETICS', 'Diuretics'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('HORMONES', 'Hormones'), ('IMMUNOSUPPRESSANTS', 'Immunosuppressants'), ('LIPID_LOWERING', 'Lipid-lowering'), ('MUSCLE_RELAXANTS', 'Muscle Relaxants'), ('NSAIDS', 'NSAIDs'), ('OPIOIDS', 'Opioids'), ('OPHTHALMICS', 'Ophthalmics'), ('PSYCHOTROPICS', 'Psychotropics'), ('SEDATIVES_HYPNOTICS', 'Sedatives/Hypnotics'), ('THYROID_PREPARATIONS', 'Thyroid Preparations'), ('VACCINES', 'Vaccines'), ('VITAMINS_MINERALS', 'Vitamins and Minerals'), ('OTHER', 'Other')], max_length=200, verbose_name='CLASS OF DRUG'),
        ),
    ]
