# Generated by Django 5.0.1 on 2024-10-20 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0002_prescription_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.prescription'),
        ),
    ]
