# Generated by Django 5.0.1 on 2024-11-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_alter_patientdata_tribe'),
        ('pharm', '0002_box_dispensarylocker_unit_remove_drug_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='dispenserecord',
            name='patient_info',
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_drugs', to='ehr.patientdata'),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary', to='pharm.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispense_unit', to='pharm.unit'),
        ),
        migrations.DeleteModel(
            name='Dispensary',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
