# Generated by Django 5.0.1 on 2024-05-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0020_alter_medicalrecord_payment'),
        ('pharm', '0002_rename_dispense_date_dispensary_dispensed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='record',
            name='balance',
        ),
        migrations.AddField(
            model_name='drug',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_drugs', to='ehr.patientdata'),
        ),
    ]
