# Generated by Django 5.0.1 on 2024-05-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0020_alter_medicalrecord_payment'),
        ('pharm', '0003_remove_dispensary_balance_remove_record_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='total_issued',
            field=models.PositiveIntegerField(default=0, verbose_name='TOTAL QTY ISSUED'),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharm_payment', to='ehr.paypoint'),
        ),
    ]
