# Generated by Django 5.0.1 on 2024-10-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0003_dispensary_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='prescription',
        ),
    ]
