# Generated by Django 5.0.1 on 2024-05-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0004_drug_total_issued_alter_dispensary_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
