# Generated by Django 5.0.1 on 2024-10-21 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0004_remove_dispensary_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dispensed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.dispensary'),
        ),
    ]
