# Generated by Django 5.0.1 on 2024-11-17 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_alter_patientdata_tribe'),
        ('pharm', '0004_rename_generic_name_drug_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserecord',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_rel', to='pharm.prescription'),
        ),
        migrations.CreateModel(
            name='Dispensary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY TO DISPENSE')),
                ('dispensed_date', models.DateTimeField(auto_now_add=True, verbose_name='DISPENSE DATE')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='REMARKS')),
                ('quantity_deducted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_drug_catgory', to='pharm.category')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_by', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_drug', to='pharm.drug')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed', to='ehr.patientdata')),
                ('prescription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary', to='pharm.prescription')),
            ],
            options={
                'verbose_name_plural': 'dispensary record',
            },
        ),
    ]
