# Generated by Django 5.0.1 on 2024-10-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0005_dispensary_dispensed_alter_prescription_dispensed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='dispensed',
            new_name='status',
        ),
    ]
