# Generated by Django 5.0.1 on 2024-11-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0005_alter_dispenserecord_prescription_dispensary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Dispensary',
        ),
    ]
