# Generated by Django 5.0.1 on 2024-05-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0005_dispensary_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='status',
        ),
    ]
