# Generated by Django 5.0.1 on 2024-05-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0006_remove_dispensary_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensary',
            options={},
        ),
        migrations.AddField(
            model_name='dispensary',
            name='quantity_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
