# Generated by Django 5.0.1 on 2024-10-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0006_rename_dispensed_prescription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
    ]
