# Generated by Django 5.0.1 on 2024-11-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0013_remove_privatebill_theatre_booking'),
        ('pharm', '0007_remove_prescription_patient_card_prescription_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='card',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drugs', to='ehr.patientdata'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
