# Generated by Django 5.0.1 on 2024-05-17 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0021_delete_prescription'),
        ('pharm', '0007_alter_dispensary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensary',
            options={'verbose_name_plural': 'dispensary record'},
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY')),
                ('updated', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='REMARKS')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drug_catgory', to='pharm.category')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drug', to='pharm.drug')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drugs', to='ehr.patientdata')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'prescription record',
            },
        ),
    ]
