# Generated by Django 5.0.1 on 2024-10-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0008_prescription_status_alter_dispensary_dispensed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
