# Generated by Django 5.0.1 on 2024-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0008_alter_dispensary_options_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensary',
            name='dispensed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DISPENSE DATE'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DATE DRUG WAS ISSUED'),
        ),
    ]
