# Generated by Django 5.0.1 on 2024-12-05 19:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0008_remove_prescription_card_prescription_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the specific drug in this prescription', validators=[django.core.validators.MinValueValidator(1)])),
                ('dosage', models.CharField(blank=True, help_text='Optional specific dosage for this drug', max_length=200, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_instances', to='pharm.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_drugs', to='pharm.prescription')),
            ],
            options={
                'verbose_name_plural': 'Prescription Drugs',
                'unique_together': {('prescription', 'drug')},
            },
        ),
    ]
