# Generated by Django 5.0.1 on 2024-12-06 06:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0009_prescriptiondrug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_dispensary', to='pharm.dispensarylocker'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispense_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='dosage',
            field=models.CharField(blank=True, help_text='Specific dosage instructions', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the specific drug', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
