# Generated by Django 5.0.1 on 2024-10-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0009_remove_prescription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='dispensed',
        ),
        migrations.AddField(
            model_name='dispensary',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensary', to='pharm.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
