# Generated by Django 5.0.1 on 2024-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0009_alter_dispensary_dispensed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
