# Generated by Django 5.0.1 on 2024-05-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0010_prescription_dispensed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensary',
            name='dispensed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharm.prescription'),
        ),
    ]
