# Generated by Django 5.0.1 on 2024-12-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0010_prescription_dispensary_prescription_dispense_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dispensary',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dispense_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dispensed_by',
        ),
    ]
