# Generated by Django 5.0.1 on 2024-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0010_remove_dispensary_dispensed_dispensary_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescribed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
