# Generated by Django 5.0.1 on 2024-05-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0011_dispensary_dispensed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='dispensed',
        ),
    ]
