# Generated by Django 5.0.1 on 2024-12-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0011_remove_prescription_dispensary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(blank=True, choices=[('expiry box', 'expiry box'), ('damaged box', 'damaged box'), ('others', 'others')], max_length=200, null=True),
        ),
    ]
