# Generated by Django 5.0.1 on 2024-06-19 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0042_remove_profile_middle_name_remove_profile_title'),
        ('pharm', '0012_remove_dispensary_dispensed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='payment',
        ),
        migrations.AddField(
            model_name='dispensary',
            name='prescribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='pharm.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharm_payment', to='ehr.paypoint'),
        ),
    ]
