# Generated by Django 5.1.6 on 2025-06-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0037_remove_clinicalnote_appointment'),
        ('pharm', '0012_alter_box_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='clinic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharm_unit', to='ehr.clinic'),
        ),
    ]
