# Generated by Django 5.0.1 on 2024-06-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0013_remove_dispensary_payment_dispensary_prescribe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensary',
            name='prescribe',
        ),
    ]
