# Generated by Django 5.1.6 on 2025-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0013_unit_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserecord',
            name='dispense_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
