# Generated by Django 5.1.6 on 2025-06-29 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0014_alter_dispenserecord_dispense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='seen_at',
            field=models.DateTimeField(blank=True, help_text='When was this prescription seen by ward?', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='seen_by',
            field=models.ForeignKey(blank=True, help_text='Who saw this prescription?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='seen_by_ward',
            field=models.BooleanField(default=False, help_text='Has this prescription been seen by ward staff?'),
        ),
    ]
