# Generated by Django 5.0.1 on 2024-11-14 22:35

import django.core.validators
import django.db.models.deletion
import django_quill.fields
import ehr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_medication', models.CharField(max_length=100, null=True)),
                ('allergies', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('qty', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('new registration', 'new registration'), ('follow up', 'follow up'), ('card replacement', 'card replacement')], max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'medical record',
            },
        ),
        migrations.CreateModel(
            name='PastSurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery', models.CharField(max_length=100, null=True)),
                ('when', models.CharField(max_length=100, null=True)),
                ('where', models.CharField(max_length=100, null=True)),
                ('LA_GA', models.CharField(max_length=100, null=True, verbose_name='L.A/G.A')),
                ('outcome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateTheatreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('qty', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheatreItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'theatre item categories',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.consumable')),
            ],
        ),
        migrations.CreateModel(
            name='ImplantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('implant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.implant')),
            ],
        ),
        migrations.CreateModel(
            name='NursingDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_desk', to='ehr.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', ehr.models.SerialNumberField(blank=True, default='', editable=False, max_length=20)),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Alhaji', 'Alhaji'), ('Mallam', 'Mallam'), ('Chief', 'Chief'), ('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Ach.', 'Ach.')], max_length=10, null=True)),
                ('last_name', models.CharField(max_length=300, null=True, verbose_name='SURNAME')),
                ('first_name', models.CharField(max_length=300, null=True)),
                ('other_name', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(max_length=22, null=True, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('marital_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED'), ('DIVORCEE', 'DIVORCEE'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER')], max_length=100, null=True)),
                ('nationality', models.CharField(choices=[('NIGERIAN', 'NIGERIAN'), ('NON-CITIZEN', 'NON-CITIZEN')], max_length=200, null=True)),
                ('zone', models.CharField(choices=[('NORTH-EAST', 'NORTH-EAST'), ('NORTH-WEST', 'NORTH-WEST'), ('NORTH-CENTRAL', 'NORTH-CENTRAL'), ('SOUTH-EAST', 'SOUTH-EAST'), ('SOUTH-WEST', 'SOUTH-WEST'), ('SOUTH-SOUTH', 'SOUTH-SOUTH')], max_length=300, null=True)),
                ('state', models.CharField(max_length=300, null=True)),
                ('lga', models.CharField(max_length=300, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('religion', models.CharField(blank=True, choices=[('ISLAM', 'ISLAM'), ('CHRISTIANITY', 'CHRISTIANITY'), ('TRADITIONAL', 'TRADITIONAL'), ('OTHER', 'OTHER')], max_length=100, null=True)),
                ('tribe', models.CharField(blank=True, choices=[('HAUSA', 'Hausa'), ('IGBO', 'Igbo'), ('IBIRA', 'Ibira'), ('FULANI', 'Fulani'), ('KANURI', 'Kanuri'), ('IJAW', 'Ijaw'), ('TIV', 'Tiv'), ('NUPE', 'Nupe'), ('EFIK', 'Efik'), ('IDOMA', 'Idoma'), ('IBIBIO', 'Ibibio'), ('IGALA', 'Igala'), ('ANNANG', 'Annang'), ('EBIRA', 'Ebira'), ('JUKUN', 'Jukun'), ('BINI', 'Bini'), ('GWARi', 'Gwari'), ('KURAMA', 'Kurama'), ('ANGAS', 'Angas'), ('BACHAMA', 'Bachama'), ('MBULA', 'Mbula'), ('KAGORO', 'Kagoro'), ('KAMUKU', 'Kamuku'), ('TAROK', 'Tarok'), ('BIROM', 'Birom'), ('BURA', 'Bura'), ('MARGI', 'Margi'), ('SHUA', 'Shua'), ('AWORI', 'Awori'), ('EKITI', 'Ekiti'), ('IJEBU', 'Ijebu'), ('IKALE', 'Ikale'), ('ILORIN', 'Ilorin'), ('ONDO', 'Ondo'), ('OSHOGBO', 'Oshogbo'), ('OYO', 'Oyo'), ('YAGBA', 'Yagba'), ('KABBA', 'Kabba'), ('Other', 'other')], max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=300, null=True)),
                ('role_in_occupation', models.CharField(blank=True, max_length=300, null=True)),
                ('nok_name', models.CharField(max_length=300, null=True, verbose_name='name')),
                ('nok_phone', models.CharField(max_length=22, null=True, unique=True, verbose_name='phone')),
                ('nok_rel', models.CharField(choices=[('SPOUSE', 'SPOUSE'), ('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('UNCLE', 'UNCLE'), ('AUNT', 'AUNT'), ('NEPHEW', 'NEPHEW'), ('NIECE', 'NIECE'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHTER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDAUGHTER'), ('COUSIN', 'COUSIN'), ('FRIEND', 'FRIEND'), ('OTHER', 'OTHER')], max_length=300, null=True, verbose_name='relationship')),
                ('nok_addr', models.CharField(blank=True, choices=[('SAME', 'SAME'), ('DIFFERENT ADDRESS', 'DIFFERENT ADDRESS')], max_length=300, null=True, verbose_name='address')),
                ('nok_addr_if', models.CharField(blank=True, max_length=300, null=True, verbose_name='address if different')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'patients data',
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_quill.fields.QuillField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('appointment', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='ehr.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery_bill', to='ehr.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to='patient_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_archive', to='ehr.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='Paypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'CASH'), ('WALLET', 'WALLET')], default='CASH', max_length=10, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_payments', to='ehr.patientdata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Physio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patientdata')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physio_payment', to='ehr.paypoint')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_bill', to='ehr.patientdata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_bill_payment', to='ehr.paypoint')),
                ('private_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_items', to='ehr.privatebill')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.privatetheatreitem')),
            ],
        ),
        migrations.CreateModel(
            name='RadiologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('cleared', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_results', to='ehr.patientdata')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_result_payment', to='ehr.paypoint')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ehr.radiologytest')),
            ],
            options={
                'verbose_name_plural': 'radiology results',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_rooms', to='ehr.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'general services',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='ehr.patientdata')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.team')),
            ],
        ),
        migrations.CreateModel(
            name='OperationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operated', models.BooleanField(default=False)),
                ('notes', django_quill.fields.QuillField(blank=True, null=True)),
                ('type_of_anaesthesia', models.CharField(blank=True, choices=[('GENERAL ANAESTHESIA', 'GENERAL ANAESTHESIA'), ('SPINE ANAESTHESIA', 'SPINE ANAESTHESIA')], max_length=300, null=True)),
                ('findings', models.CharField(blank=True, max_length=300, null=True)),
                ('post_op_order', models.CharField(blank=True, max_length=300, null=True, verbose_name='post-op order')),
                ('prescription', django_quill.fields.QuillField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_notes', to='ehr.patientdata')),
                ('theatre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre')),
            ],
            options={
                'verbose_name_plural': 'operation notes',
            },
        ),
        migrations.CreateModel(
            name='AnaesthisiaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_medical_history', models.TextField(null=True)),
                ('transfussion', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('denctures', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('permanent', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('temporary', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('loose_teeth', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('comment', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.drughistory')),
                ('last_meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.lastmeal')),
                ('concurrent_medical_illness', models.ManyToManyField(blank=True, to='ehr.medicalillness')),
                ('past_surgical_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.pastsurgicalhistory')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anaesthesia_checklist', to='ehr.patientdata')),
                ('social_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.socialhistory')),
                ('theatre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('operation_planned', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('blood_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('note', django_quill.fields.QuillField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_bookings', to='ehr.patientdata')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.team')),
                ('theatre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreitemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ehr.bill')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_payment', to='ehr.paypoint')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreitem')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreitemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreOperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('operation', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_operation', models.DateField(blank=True, null=True)),
                ('operation_suite', models.CharField(blank=True, max_length=50, null=True)),
                ('surgeon', models.CharField(blank=True, max_length=100, null=True)),
                ('assistant_1', models.CharField(blank=True, max_length=100, null=True)),
                ('assistant_2', models.CharField(blank=True, max_length=100, null=True)),
                ('assistant_3', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_nurse', models.CharField(blank=True, max_length=100, null=True)),
                ('circulating_nurse', models.CharField(blank=True, max_length=100, null=True)),
                ('anaesthetist', models.CharField(blank=True, max_length=100, null=True)),
                ('towel_clips', models.IntegerField(blank=True, default=0, null=True)),
                ('plain_gauze_small', models.IntegerField(blank=True, default=0, null=True)),
                ('artery_forceps', models.IntegerField(blank=True, default=0, null=True)),
                ('needles', models.IntegerField(blank=True, default=0, null=True)),
                ('large_swabs', models.IntegerField(blank=True, default=0, null=True)),
                ('tourniquet_applied', models.BooleanField(default=False)),
                ('tourniquet_time', models.TimeField(blank=True, null=True)),
                ('tourniquet_by', models.CharField(blank=True, max_length=100)),
                ('tourniquet_off_by', models.CharField(blank=True, max_length=100)),
                ('tourniquet_off_time', models.TimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consumables', models.ManyToManyField(blank=True, through='ehr.ConsumableUsage', to='ehr.consumable')),
                ('implants', models.ManyToManyField(blank=True, through='ehr.ImplantUsage', to='ehr.implant')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theatre_operation_record', to='ehr.patientdata')),
                ('theatre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.ward')),
            ],
        ),
        migrations.AddField(
            model_name='implantusage',
            name='surgical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreoperationrecord'),
        ),
        migrations.AddField(
            model_name='consumableusage',
            name='surgical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreoperationrecord'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.unit')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitals', models.BooleanField(default=False)),
                ('consultation', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic')),
                ('nursing_desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.nursingdesk')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_record', to='ehr.patientdata')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_payment', to='ehr.paypoint')),
                ('record', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='ehr.medicalrecord')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.room')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.team')),
            ],
            options={
                'verbose_name_plural': 'visit record',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('pulse_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('respiration_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_oxygen', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_glucose', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='ehr.patientdata')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vital signs',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='ehr.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ehr.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ADMIT', 'ADMIT'), ('RECEIVED', 'RECEIVED'), ('DISCHARGE', 'DISCHARGE')], default='ADMIT', max_length=30, null=True)),
                ('bed_number', models.CharField(blank=True, max_length=300, null=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_info', to='ehr.patientdata')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WardClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_quill.fields.QuillField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_clinical_notes', to='ehr.patientdata')),
            ],
            options={
                'verbose_name_plural': 'ward notes',
            },
        ),
        migrations.CreateModel(
            name='WardMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(blank=True, max_length=10, null=True)),
                ('dose', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.CharField(blank=True, max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_medication', to='ehr.patientdata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ward vital signs',
            },
        ),
        migrations.CreateModel(
            name='WardShiftSUmmaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_quill.fields.QuillField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ward shift summary notes',
            },
        ),
        migrations.CreateModel(
            name='WardVitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('pulse_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('respiration_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_oxygen', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_glucose', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_vital_signs', to='ehr.patientdata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ward vital signs',
            },
        ),
    ]
