# Generated by Django 5.0.1 on 2024-05-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
