# Generated by Django 5.0.1 on 2024-07-12 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='theatreitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='theatreitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='theatreitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='theatreitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ehr.bill')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreitem')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreitemcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
