# Generated by Django 5.0.1 on 2024-09-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_visitrecord_clinical_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrecord',
            name='clinical_note',
        ),
    ]
