# Generated by Django 5.0.1 on 2024-05-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_rename_unit_profile_unit_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='patient',
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_handovers', to='ehr.clinic'),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_handover', to='ehr.room'),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_handover', to='ehr.team'),
        ),
        migrations.AlterField(
            model_name='room',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_rooms', to='ehr.clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='patienthandover',
            unique_together={('patient', 'clinic', 'room')},
        ),
    ]
