# Generated by Django 5.0.1 on 2024-05-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_room_patienthandover_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
    ]
