# Generated by Django 5.0.1 on 2024-11-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_paypoint_unit_alter_paypoint_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypoint',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
