# Generated by Django 5.0.1 on 2024-06-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_clinic_room_theatre_alter_appointment_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatrenotes',
            options={'verbose_name_plural': 'theare notes'},
        ),
        migrations.AddField(
            model_name='patientdata',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic'),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('NHIS.', 'NHIS.'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
