# Generated by Django 5.0.1 on 2024-07-12 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_theatreitemcategory_remove_theatreitem_bill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatreitemcategory',
            options={'verbose_name_plural': 'theatre item categories'},
        ),
        migrations.AddField(
            model_name='theatreitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreitemcategory'),
        ),
    ]
