# Generated by Django 5.0.1 on 2024-07-15 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_room_alter_patienthandover_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic'),
        ),
    ]
