# Generated by Django 5.0.1 on 2024-07-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_alter_theatreitemcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatreitem',
            old_name='name',
            new_name='item',
        ),
    ]
