# Generated by Django 5.0.1 on 2024-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_remove_visitrecord_clinical_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_addr',
            field=models.CharField(blank=True, choices=[('SAME', 'SAME'), ('DIFFERENT ADDRESS', 'DIFFERENT ADDRESS')], max_length=300, null=True, verbose_name='next of kin address'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_phone',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True, verbose_name='next of kin phone'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_rel',
            field=models.CharField(blank=True, choices=[('SPOUSE', 'SPOUSE'), ('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('UNCLE', 'UNCLE'), ('AUNT', 'AUNT'), ('NEPHEW', 'NEPHEW'), ('NIECE', 'NIECE'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHTER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDAUGHTER'), ('COUSIN', 'COUSIN'), ('FRIEND', 'FRIEND'), ('OTHER', 'OTHER')], max_length=300, null=True, verbose_name='relationship with next of kin'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='phone',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
    ]
