# Generated by Django 5.0.1 on 2024-11-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_alter_paypoint_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='tribe',
            field=models.CharField(blank=True, choices=[('HAUSA', 'Hausa'), ('YORUBA', 'Yoruba'), ('IGBO', 'Igbo'), ('IBIRA', 'Ibira'), ('FULANI', 'Fulani'), ('KANURI', 'Kanuri'), ('IJAW', 'Ijaw'), ('TIV', 'Tiv'), ('NUPE', 'Nupe'), ('EFIK', 'Efik'), ('IDOMA', 'Idoma'), ('IBIBIO', 'Ibibio'), ('IGALA', 'Igala'), ('ANNANG', 'Annang'), ('EBIRA', 'Ebira'), ('JUKUN', 'Jukun'), ('BINI', 'Bini'), ('GWARi', 'Gwari'), ('KURAMA', 'Kurama'), ('ANGAS', 'Angas'), ('BACHAMA', 'Bachama'), ('MBULA', 'Mbula'), ('KAGORO', 'Kagoro'), ('KAMUKU', 'Kamuku'), ('TAROK', 'Tarok'), ('BIROM', 'Birom'), ('BURA', 'Bura'), ('MARGI', 'Margi'), ('SHUA', 'Shua'), ('AWORI', 'Awori'), ('EKITI', 'Ekiti'), ('IJEBU', 'Ijebu'), ('IKALE', 'Ikale'), ('ILORIN', 'Ilorin'), ('ONDO', 'Ondo'), ('OSHOGBO', 'Oshogbo'), ('OYO', 'Oyo'), ('YAGBA', 'Yagba'), ('KABBA', 'Kabba'), ('Other', 'other')], max_length=100, null=True),
        ),
    ]
