# Generated by Django 5.0.1 on 2024-05-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_remove_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_team', to='ehr.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('purple', 'purple'), ('white', 'white'), ('blue', 'blue'), ('pink', 'pink'), ('plastic', 'plastic'), ('club foot', 'club foot')], max_length=200, null=True),
        ),
    ]
