# Generated by Django 5.0.1 on 2024-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_alter_theatrenotes_options_patientdata_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='payment',
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='next of kin phone'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('NHIS', 'NHIS'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
