# Generated by Django 5.0.1 on 2024-07-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_patientdata_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='payment',
        ),
    ]
