# Generated by Django 5.0.1 on 2024-05-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_remove_clinicalnote_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_drugs', to='ehr.patientdata'),
        ),
    ]
