# Generated by Django 5.0.1 on 2024-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_remove_room_patient_alter_patienthandover_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='title',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD'), ('SPINE SOPD', 'SPINE SOPD'), ('GOPD', 'GOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='room',
            field=models.CharField(choices=[('ROOM 1', 'ROOM 1'), ('ROOM 2', 'ROOM 2'), ('ROOM 3', 'ROOM 3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('seen_by_doctor', 'seen_by_doctor'), ('awaiting_review', 'awaiting_review')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='team',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=30, null=True),
        ),
    ]
