# Generated by Django 5.0.1 on 2024-04-03 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_paypoint_amount_alter_paypoint_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='pay_status',
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='Phatology',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='prescription',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='radiology',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='icu',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='nhis',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='pando',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='paypoint',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='phatology',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='physio',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='radiology',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='theatre',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='visit',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='ward',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
    ]
