# Generated by Django 5.0.1 on 2024-05-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_alter_clinic_team_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_teams', to='ehr.clinic'),
        ),
        migrations.AlterField(
            model_name='room',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='ehr.clinic'),
        ),
    ]
