# Generated by Django 5.0.1 on 2024-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_alter_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs'), ('Miss', 'Miss'), ('Alhaji', 'Alhaji'), ('Mallam', 'Mallam'), ('Chief', 'Chief'), ('Prof.', 'Prof'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Ach', 'Ach')], max_length=10, null=True),
        ),
    ]
