# Generated by Django 5.0.1 on 2024-05-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_alter_patientdata_title_alter_patienthandover_clinic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPDClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Clinic',
            new_name='AEClinic',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='room',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD'), ('SPINE SOPD', 'SPINE SOPD'), ('GOPD', 'GOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='followupvisit',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD'), ('SPINE SOPD', 'SPINE SOPD'), ('GOPD', 'GOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD'), ('SPINE SOPD', 'SPINE SOPD'), ('GOPD', 'GOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD'), ('SPINE SOPD', 'SPINE SOPD'), ('GOPD', 'GOPD')], max_length=30, null=True),
        ),
    ]
