# Generated by Django 5.0.1 on 2024-11-20 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_alter_patientdata_tribe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patientdata'),
        ),
        migrations.AddField(
            model_name='billing',
            name='theatre_booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='theatre_booking_time',
            field=models.TimeField(null=True),
        ),
    ]
