# Generated by Django 5.0.1 on 2024-07-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_rename_name_theatreitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatreitem',
            old_name='item',
            new_name='name',
        ),
    ]
