# Generated by Django 5.0.1 on 2024-11-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_appointment_time_alter_patientdata_nok_addr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
