# Generated by Django 5.0.1 on 2024-07-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_remove_medicalrecord_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_rooms', to='ehr.clinic'),
        ),
        migrations.CreateModel(
            name='NursingDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_desk', to='ehr.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='patienthandover',
            name='nursing_desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.nursingdesk'),
        ),
    ]
