# Generated by Django 5.0.1 on 2024-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0004_remove_medicalrecord_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthandover',
            name='room',
            field=models.CharField(choices=[('ROOM 1', 'ROOM 1'), ('ROOM 2', 'ROOM 2'), ('ROOM 3', 'ROOM 3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='room',
            field=models.CharField(choices=[('ROOM 1', 'ROOM 1'), ('ROOM 2', 'ROOM 2'), ('ROOM 3', 'ROOM 3')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
