# Generated by Django 5.0.1 on 2024-07-15 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0005_room_clinic_nursingdesk_patienthandover_nursing_desk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthandover',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.room'),
        ),
    ]
