# Generated by Django 5.0.1 on 2024-05-04 20:03

import django.db.models.deletion
import ehr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0005_remove_appointment_status_alter_patientdata_nok_rel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalnote',
            old_name='Phatology',
            new_name='phatology',
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='ehr.patientdata'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='file_no',
            field=ehr.models.SerialNumberField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vatal_signs', to='ehr.patientdata'),
        ),
    ]
