# Generated by Django 5.0.1 on 2024-11-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0005_rename_updated_at_appointment_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='patient_type',
        ),
        migrations.AddField(
            model_name='patientdata',
            name='nok_addr_if',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='next of kin address if not same'),
        ),
    ]
