# Generated by Django 5.0.1 on 2024-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0005_alter_patientdata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Alhaji', 'Alhaji'), ('Mallam', 'Mallam'), ('Chief', 'Chief'), ('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Ach.', 'Ach.')], max_length=10, null=True),
        ),
    ]
