# Generated by Django 5.0.1 on 2024-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0005_sopdclinic_rename_clinic_aeclinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupvisit',
            name='team',
        ),
        migrations.RemoveField(
            model_name='patienthandover',
            name='team',
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='room',
            field=models.CharField(choices=[('ROOM 1', 'ROOM 1'), ('ROOM 2', 'ROOM 2'), ('ROOM 3', 'ROOM 3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='team',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=30, null=True),
        ),
    ]
