# Generated by Django 5.0.1 on 2024-11-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0005_billing_doctor_billing_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='theatre_booking_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='theatre_booking_time',
        ),
        migrations.AddField(
            model_name='billing',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='operation_planned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.team'),
        ),
        migrations.AddField(
            model_name='billing',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre'),
        ),
    ]
