# Generated by Django 5.0.1 on 2024-11-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_rename_theatre_booking_date_billing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='operation_planned',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='team',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='theatre',
        ),
    ]
