# Generated by Django 5.0.1 on 2024-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_remove_followupvisit_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
