# Generated by Django 5.0.1 on 2024-06-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_alter_patienthandover_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='clinic',
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='followupvisit',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='theatrebooking',
            name='theatre',
            field=models.CharField(choices=[('MAIN THEATRE', 'MAIN THEATRE'), ('SPINE THEATRE', 'SPINE THEATRE')], max_length=30, null=True),
        ),
        migrations.AlterModelOptions(
            name='theatrenotes',
            options={},
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='type',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_payment', to='ehr.paypoint'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='team',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_phone',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='next of kin phone'),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('complete', 'complete'), ('await_review', 'await review')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='theatrebooking',
            name='team',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
