# Generated by Django 5.0.1 on 2024-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_billing_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='price',
        ),
        migrations.AddField(
            model_name='theatreitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
