# Generated by Django 5.0.1 on 2024-07-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_alter_patienthandover_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_medication', models.CharField(max_length=100, null=True)),
                ('allergies', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('qty', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastSurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery', models.CharField(max_length=100, null=True)),
                ('when', models.CharField(max_length=100, null=True)),
                ('where', models.CharField(max_length=100, null=True)),
                ('LA_GA', models.CharField(max_length=100, null=True, verbose_name='L.A/G.A')),
                ('outcome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('qty', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='denctures',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='loose_teeth',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='past_medical_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='permanent',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='temporary',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='transfussion',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operatingtheatre',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operatingtheatre',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_theatre', to='ehr.patientdata'),
        ),
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theatre_operation_record', to='ehr.patientdata'),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='drug_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.drughistory'),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='last_meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.lastmeal'),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='concurrent_medical_illness',
            field=models.ManyToManyField(blank=True, null=True, to='ehr.medicalillness'),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='past_surgical_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.pastsurgicalhistory'),
        ),
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='social_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.socialhistory'),
        ),
    ]
