# Generated by Django 5.0.1 on 2024-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_alter_patientdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='handover_status',
            field=models.CharField(choices=[('seen', 'seen'), ('review', 'review')], default='seen', max_length=10),
        ),
    ]
