# Generated by Django 5.0.1 on 2024-05-04 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_rename_phatology_clinicalnote_phatology_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='TYPE OF SERVICE')),
            ],
            options={
                'verbose_name_plural': 'hospital services',
            },
        ),
        migrations.AlterModelOptions(
            name='patientdata',
            options={'verbose_name_plural': 'patients data'},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(blank=True, choices=[('A & E', 'A & E'), ('SOPD', 'SOPD'), ('SPINE SOPD', 'SPINE SOPD'), ('GOPD', 'GOPD'), ('NHIS', 'NHIS'), ('DENTAL', 'DENTAL'), ('O & G', 'O & G'), ('UROLOGY', 'UROGOLY'), ('DERMATOLOGY', 'DERMATOLOGY'), ('PAEDIATRY', 'PAEDIATRY')], default='A & E', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='ehr.patientdata'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.servicetype')),
            ],
        ),
    ]
