# Generated by Django 5.0.1 on 2024-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0006_remove_patientdata_patient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='dob',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='lga',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED'), ('DIVORCEE', 'DIVORCEE'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nationality',
            field=models.CharField(choices=[('NIGERIAN', 'NIGERIAN'), ('NON-CITIZEN', 'NON-CITIZEN')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_addr',
            field=models.CharField(blank=True, choices=[('SAME', 'SAME'), ('DIFFERENT ADDRESS', 'DIFFERENT ADDRESS')], max_length=300, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_addr_if',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='address if different'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_name',
            field=models.CharField(max_length=300, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_phone',
            field=models.CharField(max_length=22, null=True, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_rel',
            field=models.CharField(choices=[('SPOUSE', 'SPOUSE'), ('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('UNCLE', 'UNCLE'), ('AUNT', 'AUNT'), ('NEPHEW', 'NEPHEW'), ('NIECE', 'NIECE'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHTER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDAUGHTER'), ('COUSIN', 'COUSIN'), ('FRIEND', 'FRIEND'), ('OTHER', 'OTHER')], max_length=300, null=True, verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='other_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='phone',
            field=models.CharField(max_length=22, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='religion',
            field=models.CharField(choices=[('ISLAM', 'ISLAM'), ('CHRISTIANITY', 'CHRISTIANITY'), ('TRADITIONAL', 'TRADITIONAL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='state',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='zone',
            field=models.CharField(choices=[('NORTH-EAST', 'NORTH-EAST'), ('NORTH-WEST', 'NORTH-WEST'), ('NORTH-CENTRAL', 'NORTH-CENTRAL'), ('SOUTH-EAST', 'SOUTH-EAST'), ('SOUTH-WEST', 'SOUTH-WEST'), ('SOUTH-SOUTH', 'SOUTH-SOUTH')], max_length=300, null=True),
        ),
    ]
