# Generated by Django 5.0.1 on 2024-11-20 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_remove_billing_date_remove_billing_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='operation_planned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.team'),
        ),
        migrations.AddField(
            model_name='billing',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre'),
        ),
    ]
