# Generated by Django 5.0.1 on 2024-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_remove_patientdata_clinic_alter_vitalsigns_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('f_waiting_for_payment', 'F Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('complete', 'complete'), ('await_review', 'await review')], max_length=30, null=True),
        ),
    ]
