# Generated by Django 5.0.1 on 2024-05-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_clinicalnote_handover_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalnote',
            name='handover_status',
        ),
    ]
