# Generated by Django 5.0.1 on 2024-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_alter_patientdata_address_alter_patientdata_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='last_name',
            field=models.CharField(max_length=300, null=True, verbose_name='SURNAME'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='other_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Alhaji', 'Alhaji'), ('Mallam', 'Mallam'), ('Chief', 'Chief'), ('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Ach.', 'Ach.')], max_length=10, null=True),
        ),
    ]
