# Generated by Django 5.0.1 on 2024-05-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_servicetype_alter_patientdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypoint',
            name='amount',
        ),
        migrations.AlterField(
            model_name='paypoint',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.services'),
        ),
    ]
