# Generated by Django 5.0.1 on 2024-05-10 20:18

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0007_remove_appointment_appointment_date_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='note',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
