# Generated by Django 5.0.1 on 2024-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_alter_patientdata_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='first_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'ISLAM'), ('CHRISTIANITY', 'CHRISTIANITY'), ('TRADITIONAL', 'TRADITIONAL'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Alhaji', 'Alhaji'), ('Mallam', 'Mallam'), ('Chief', 'Chief'), ('Prof.', 'Prof.'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Ach.', 'Ach.')], max_length=10, null=True),
        ),
    ]
