# Generated by Django 5.0.1 on 2024-05-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_remove_paypoint_amount_alter_paypoint_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'hospital services'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={},
        ),
        migrations.RemoveField(
            model_name='services',
            name='user',
        ),
    ]
