# Generated by Django 5.0.1 on 2024-05-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_alter_clinicalnote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('seen', 'seen'), ('awaiting_review', 'awaiting_review')], max_length=30, null=True),
        ),
    ]
