# Generated by Django 5.0.1 on 2024-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_alter_patienthandover_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterModelOptions(
            name='theatrenotes',
            options={'verbose_name_plural': 'theatre notes'},
        ),
        migrations.AddField(
            model_name='patientdata',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'REGULAR'), ('NHIS', 'NHIS'), ('RETAINER', 'RETAINER')], max_length=100, null=True),
        ),
    ]
