# Generated by Django 5.0.1 on 2024-07-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_privatetheatreitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatebilling',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='privatetheatreitem',
            name='price',
        ),
        migrations.AddField(
            model_name='privatebilling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
