# Generated by Django 5.0.1 on 2024-07-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0008_alter_billing_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ehr.bill'),
        ),
    ]
