# Generated by Django 5.0.1 on 2024-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0009_remove_privatebilling_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatePTBillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('operation_planned', models.CharField(max_length=300)),
            ],
        ),
    ]
