# Generated by Django 5.0.1 on 2024-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0009_alter_billing_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='physio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='theatreitem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='theatreitemcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
