# Generated by Django 5.0.1 on 2024-05-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0009_alter_services_options_alter_servicetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='user',
        ),
    ]
