# Generated by Django 5.0.1 on 2024-11-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0009_remove_billing_date_remove_billing_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='theatre_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.theatrebooking'),
        ),
    ]
