# Generated by Django 5.0.1 on 2024-05-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0009_clinicalnote_appointment_clinicalnote_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patienthandover'),
        ),
    ]
