# Generated by Django 5.0.1 on 2024-05-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_paypoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypoint',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
