# Generated by Django 5.0.1 on 2024-05-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_remove_vitalsigns_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patientdata'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
