# Generated by Django 5.0.1 on 2024-07-13 21:41

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_bill_updated_billing_updated_physio_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatrebooking',
            old_name='user',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='wardclinicalnote',
            old_name='user',
            new_name='doctor',
        ),
        migrations.AddField(
            model_name='theatrebooking',
            name='blood_requirement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theatrebooking',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theatrebooking',
            name='note',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theatrebooking',
            name='operation_planned',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theatrebooking',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.paypoint'),
        ),
        migrations.AlterField(
            model_name='theatrebooking',
            name='theatre',
            field=models.CharField(choices=[('A & E THEATRE', 'A & E THEATRE'), ('o & G THEATRE', 'O & G THEATRE'), ('MAIN THEATRE', 'MAIN THEATRE'), ('SPINE THEATRE', 'SPINE THEATRE')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='AnaesthisiaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anaesthesia_checklist', to='ehr.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='OperationNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operated', models.BooleanField(default=False)),
                ('notes', django_quill.fields.QuillField(blank=True, null=True)),
                ('type_of_anaesthesia', models.CharField(blank=True, choices=[('GENERAL ANAESTHESIA', 'GENERAL ANAESTHESIA'), ('SPINE ANAESTHESIA', 'SPINE ANAESTHESIA')], max_length=300, null=True)),
                ('findings', models.CharField(blank=True, max_length=300, null=True)),
                ('post_op_order', models.CharField(blank=True, max_length=300, null=True, verbose_name='post-op order')),
                ('prescription', django_quill.fields.QuillField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_notes', to='ehr.patientdata')),
            ],
            options={
                'verbose_name_plural': 'operation notes',
            },
        ),
        migrations.CreateModel(
            name='PeriOPNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peri_op_nurse', to='ehr.patientdata')),
            ],
            options={
                'verbose_name_plural': 'peri-op nurses',
            },
        ),
        migrations.CreateModel(
            name='WardShiftSUmmaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_quill.fields.QuillField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ward shift summary notes',
            },
        ),
        migrations.DeleteModel(
            name='TheatreNotes',
        ),
    ]
