# Generated by Django 5.0.1 on 2024-11-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_billing_theatre_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='theatre_booking',
        ),
        migrations.AddField(
            model_name='bill',
            name='theatre_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.theatrebooking'),
        ),
    ]
