# Generated by Django 5.0.1 on 2024-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_alter_clinicalnote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('await review', 'await review')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('consultated', 'Consultated')], max_length=30, null=True),
        ),
    ]
