# Generated by Django 5.0.1 on 2024-06-28 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_alter_patienthandover_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupvisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting for payment', 'Waiting for Payment'), ('f waiting for payment', 'F Waiting for Payment'), ('waiting for clinic assignment', 'Waiting for Clinic Assignment'), ('waiting for vital signs', 'Waiting for Vital Signs'), ('waiting for consultation', 'Waiting for Consultation'), ('Seen', 'Seen'), ('Awaiting Review', 'Awaiting Review')], max_length=30, null=True),
        ),
    ]
