# Generated by Django 5.0.1 on 2024-07-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0010_privateptbillinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivatePTBillInfo',
        ),
    ]
