# Generated by Django 5.0.1 on 2024-07-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0011_delete_privateptbillinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatebilling',
            name='booking_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='ehr.theatrebooking'),
        ),
    ]
