# Generated by Django 5.0.1 on 2024-11-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0011_remove_billing_theatre_booking_bill_theatre_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatebill',
            name='theatre_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.theatrebooking'),
        ),
    ]
