# Generated by Django 5.0.1 on 2024-05-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0011_alter_clinicalnote_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalnote',
            name='status',
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='pt_status',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_field': ['complete', 'await review']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patienthandover'),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('complete', 'Complete'), ('await review', 'Await Review')], max_length=30, null=True),
        ),
    ]
