# Generated by Django 5.0.1 on 2024-07-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0011_rename_user_theatrebooking_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingTheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(blank=True, choices=[('MALE WARD', 'MALE WARD'), ('FEMALE WARD', 'FEMALE WARD'), ('CHILDRENS WARD', 'CHILDRENS WARD'), ('ICU', 'ICU')], max_length=300, null=True)),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=300, null=True)),
                ('operation', models.CharField(blank=True, max_length=300, null=True)),
                ('surgeon', models.CharField(blank=True, max_length=100, null=True)),
                ('asst_1', models.CharField(blank=True, max_length=100, null=True)),
                ('asst_2', models.CharField(blank=True, max_length=100, null=True)),
                ('asst_3', models.CharField(blank=True, max_length=100, null=True)),
                ('scrub_nurse', models.CharField(blank=True, max_length=100, null=True)),
                ('circulating_nurse', models.CharField(blank=True, max_length=100, null=True)),
                ('anaesthetist', models.CharField(blank=True, max_length=100, null=True)),
                ('scrub_nurse_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_implant', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implants', to='ehr.operatingtheatre')),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_consumables', to='ehr.operatingtheatre')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreOperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(blank=True, max_length=300, null=True)),
                ('surgeons', models.TextField(blank=True, null=True)),
                ('assistant', models.TextField(blank=True, null=True)),
                ('instrument_nurse', models.CharField(blank=True, max_length=300, null=True)),
                ('anaesthetist', models.CharField(blank=True, max_length=300, null=True)),
                ('anaesthetic', models.CharField(blank=True, max_length=300, null=True)),
                ('circulation', models.CharField(blank=True, max_length=300, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatrebooking')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('SWABS', 'Swabs & Instrument Count'), ('TOWEL', 'Towel Clips'), ('GAUZE', 'Pack Gauze Small'), ('ARTERY', 'Artery Forceps'), ('NEEDLES', 'Needles'), ('LARGE_SWABS', 'Large Swabs')], max_length=20)),
                ('stage', models.CharField(choices=[('BEFORE', 'Before Operation'), ('DURING', 'During Operation'), ('TOTAL', 'Total at the End')], max_length=10)),
                ('count', models.IntegerField()),
                ('operation_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_counts', to='ehr.theatreoperationrecord')),
            ],
            options={
                'unique_together': {('operation_record', 'item', 'stage')},
            },
        ),
    ]
