# Generated by Django 5.0.1 on 2024-05-06 14:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0012_appointment_user_clinic_user_patienthandover_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
