# Generated by Django 5.0.1 on 2024-05-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0012_remove_clinicalnote_status_clinicalnote_pt_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalnote',
            name='pt_status',
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('complete', 'complete'), ('await_review', 'await review')], max_length=30, null=True),
        ),
    ]
