# Generated by Django 5.0.1 on 2024-11-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0012_privatebill_theatre_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatebill',
            name='theatre_booking',
        ),
    ]
