# Generated by Django 5.0.1 on 2024-05-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0012_alter_followupvisit_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD'), ('SPINE SOPD', 'SPINE SOPD'), ('GOPD', 'GOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('ROOM 1', 'ROOM 1'), ('ROOM 2', 'ROOM 2'), ('ROOM 3', 'ROOM 3')], max_length=30, null=True),
        ),
    ]
