# Generated by Django 5.0.1 on 2024-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0012_appointment_user_clinic_user_patienthandover_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='note',
            field=models.TextField(blank=True, max_length=500000, null=True),
        ),
    ]
