# Generated by Django 5.0.1 on 2024-11-23 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0013_remove_privatebill_theatre_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='ward',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, help_text='Daily charge for this ward', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='paypoint',
            index=models.Index(fields=['patient', 'unit', 'status', 'created'], name='ehr_paypoin_patient_72a6df_idx'),
        ),
        migrations.AddField(
            model_name='admissioncharge',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='ehr.admission'),
        ),
        migrations.AddField(
            model_name='admissioncharge',
            name='paypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_charges', to='ehr.paypoint'),
        ),
        migrations.AlterUniqueTogether(
            name='admissioncharge',
            unique_together={('admission', 'charge_date')},
        ),
    ]
