# Generated by Django 5.0.1 on 2024-05-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0013_vitalsigns_clinic_alter_room_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patienthandover',
            unique_together=set(),
        ),
    ]
