# Generated by Django 5.0.1 on 2024-07-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0013_remove_privatebilling_booking_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypoint',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('WALLET', 'Wallet')], default='CASH', max_length=10, null=True),
        ),
    ]
