# Generated by Django 5.0.1 on 2024-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0014_alter_patienthandover_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AEClinic',
        ),
        migrations.DeleteModel(
            name='SOPDClinic',
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for Payment'), ('waiting_for_clinic_assignment', 'Waiting for Clinic Assignment'), ('waiting_for_vital_signs', 'Waiting for Vital Signs'), ('waiting_for_consultation', 'Waiting for Consultation'), ('seen', 'seen'), ('review', 'review')], max_length=30, null=True),
        ),
    ]
