# Generated by Django 5.0.1 on 2024-07-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0014_alter_paypoint_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypoint',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('WALLET', 'WALLET')], default='CASH', max_length=10, null=True),
        ),
    ]
