# Generated by Django 5.0.1 on 2024-11-24 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0014_admissioncharge_ward_daily_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatrebooking',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='daily_rate',
        ),
        migrations.AddField(
            model_name='admission',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_payment', to='ehr.paypoint'),
        ),
        migrations.AddField(
            model_name='ward',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='AdmissionCharge',
        ),
    ]
