# Generated by Django 5.0.1 on 2024-05-06 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0014_alter_clinicalnote_note_followvisit_delete_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowVisit',
            new_name='FollowUpVisit',
        ),
    ]
