# Generated by Django 5.0.1 on 2024-05-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0014_remove_paypoint_hematology_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypoint',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
