# Generated by Django 5.0.1 on 2024-05-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0015_rename_followvisit_followupvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='user',
        ),
    ]
