# Generated by Django 5.0.1 on 2024-05-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0015_alter_paypoint_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypoint',
            name='item',
        ),
    ]
