# Generated by Django 5.0.1 on 2024-05-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0015_delete_aeclinic_delete_sopdclinic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsigns',
            options={'verbose_name_plural': 'vital signs'},
        ),
    ]
