# Generated by Django 5.0.1 on 2024-07-28 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0015_alter_paypoint_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='operatingtheatre',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='operatingtheatre',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='surgicalconsumable',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='implant',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='periopnurse',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='periopnurse',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='implant',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='implant',
            name='type_of_implant',
        ),
        migrations.RemoveField(
            model_name='theatreoperationrecord',
            name='anaesthetic',
        ),
        migrations.RemoveField(
            model_name='theatreoperationrecord',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='theatreoperationrecord',
            name='circulation',
        ),
        migrations.RemoveField(
            model_name='theatreoperationrecord',
            name='info',
        ),
        migrations.RemoveField(
            model_name='theatreoperationrecord',
            name='surgeons',
        ),
        migrations.AddField(
            model_name='implant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='implant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='artery_forceps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='assistant_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='assistant_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='assistant_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='circulating_nurse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='date_of_operation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='large_swabs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='needles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='operation_suite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='plain_gauze_small',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='surgeon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='tourniquet_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='tourniquet_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='tourniquet_off_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='tourniquet_off_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='tourniquet_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='towel_clips',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='implant',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='anaesthetist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='instrument_nurse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='operation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ConsumableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.consumable')),
                ('surgical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreoperationrecord')),
            ],
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='consumables',
            field=models.ManyToManyField(blank=True, null=True, through='ehr.ConsumableUsage', to='ehr.consumable'),
        ),
        migrations.CreateModel(
            name='ImplantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('implant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.implant')),
                ('surgical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreoperationrecord')),
            ],
        ),
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='implants',
            field=models.ManyToManyField(blank=True, null=True, through='ehr.ImplantUsage', to='ehr.implant'),
        ),
        migrations.DeleteModel(
            name='InstrumentCount',
        ),
        migrations.DeleteModel(
            name='SurgicalConsumable',
        ),
        migrations.DeleteModel(
            name='OperatingTheatre',
        ),
        migrations.DeleteModel(
            name='PeriOPNurse',
        ),
    ]
