# Generated by Django 5.0.1 on 2024-11-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0016_physiotest_physiotestcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotestcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='radiologyresult',
            name='local_file_path',
        ),
        migrations.AlterField(
            model_name='physiorequest',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physio_info', to='ehr.patientdata'),
        ),
        migrations.AlterField(
            model_name='physiotestcategory',
            name='name',
            field=models.CharField(choices=[('manual_muscle_strength', 'Manual Muscle Strength Tests'), ('range_of_motion', 'Range of Motion Tests'), ('orthopedic', 'Orthopedic Tests'), ('neurological', 'Neurological Tests'), ('functional_capacity', 'Functional Capacity Tests'), ('pain_assessment', 'Pain Assessment Tests'), ('special_condition', 'Special Condition Tests'), ('rehabilitation_specific', 'Rehabilitation Specific Tests'), ('cardiovascular', 'Cardiovascular Tests'), ('sports_specific', 'Sports-Specific Tests'), ('specialized_orthopedic', 'Specialized Orthopedic Assessments'), ('neurological_specific', 'Neurological Specific Tests'), ('ergonomic_workplace', 'Ergonomic and Workplace Assessments'), ('pediatric', 'Pediatric Physiotherapy Tests'), ('geriatric', 'Geriatric Specific Tests')], max_length=100, unique=True),
        ),
    ]
