# Generated by Django 5.0.1 on 2024-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0016_alter_vitalsigns_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypoint',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Receipt Number'),
        ),
    ]
