# Generated by Django 5.0.1 on 2024-07-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0016_consumable_remove_operatingtheatre_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='consumables',
            field=models.ManyToManyField(blank=True, through='ehr.ConsumableUsage', to='ehr.consumable'),
        ),
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='implants',
            field=models.ManyToManyField(blank=True, through='ehr.ImplantUsage', to='ehr.implant'),
        ),
    ]
