# Generated by Django 5.0.1 on 2024-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0017_paypoint_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypoint',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
