# Generated by Django 5.0.1 on 2024-07-28 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0017_alter_theatreoperationrecord_consumables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatreoperationrecord',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre'),
        ),
    ]
