# Generated by Django 5.0.1 on 2024-05-16 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0017_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('new registration', 'new registration'), ('follow up', 'follow up'), ('card replacement', 'card replacement')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.recordservices'),
        ),
    ]
