# Generated by Django 5.0.1 on 2024-11-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0017_remove_physiotestcategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationnotes',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='physiorequest',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
