# Generated by Django 5.0.1 on 2024-05-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0018_recordservices_alter_medicalrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(blank=True, choices=[('new registration', 'new registration'), ('follow up', 'follow up'), ('card replacement', 'card replacement')], max_length=100, null=True),
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'verbose_name_plural': 'medical record'},
        ),
        migrations.DeleteModel(
            name='RecordServices',
        ),
    ]
