# Generated by Django 5.0.1 on 2024-07-28 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0018_theatreoperationrecord_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.ward'),
        ),
    ]
