# Generated by Django 5.0.1 on 2024-07-28 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0019_alter_theatreoperationrecord_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaesthisiachecklist',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre'),
        ),
        migrations.AddField(
            model_name='operationnotes',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre'),
        ),
    ]
