# Generated by Django 5.0.1 on 2024-05-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0019_alter_medicalrecord_name_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_payment', to='ehr.paypoint'),
        ),
    ]
