# Generated by Django 5.0.1 on 2024-05-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0020_alter_medicalrecord_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
