# Generated by Django 5.0.1 on 2024-07-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0020_anaesthisiachecklist_theatre_operationnotes_theatre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='accept',
            new_name='audit_clear',
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='receive',
            field=models.BooleanField(default=False),
        ),
    ]
