# Generated by Django 5.0.1 on 2024-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0021_rename_accept_admission_audit_clear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='admit',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='audit_clear',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='receive',
        ),
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('ADMIT', 'ADMIT'), ('RECEIVED', 'RECEIVED'), ('DISCHARGE', 'DISCHARGE')], max_length=30, null=True),
        ),
    ]
