# Generated by Django 5.0.1 on 2024-05-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0021_delete_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SURNAME'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='phone',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paypoint',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_payments', to='ehr.patientdata'),
        ),
    ]
