# Generated by Django 5.0.1 on 2024-12-11 20:47

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0021_remove_profile_photo_alter_paypoint_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='notes',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthisiachecklist',
            name='comment',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anaesthisiachecklist',
            name='past_medical_history',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiorequest',
            name='comment',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiorequest',
            name='result_details',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiotest',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='comments',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theatreoperationrecord',
            name='comments',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
