# Generated by Django 5.0.1 on 2024-05-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0022_alter_patientdata_last_name_alter_patientdata_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'general services'},
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
