# Generated by Django 5.0.1 on 2024-07-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0022_remove_admission_admit_remove_admission_audit_clear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='expected_discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('ADMIT', 'ADMIT'), ('RECEIVED', 'RECEIVED'), ('DISCHARGE', 'DISCHARGE')], default='ADMIT', max_length=30, null=True),
        ),
    ]
