# Generated by Django 5.0.1 on 2024-07-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0023_admission_expected_discharge_date_admission_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
