# Generated by Django 5.0.1 on 2024-12-16 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0023_radiologyinvestigations_radiologytests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyinvestigations',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.radiologytests'),
        ),
        migrations.AlterField(
            model_name='radiologyinvestigations',
            name='radiologytest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_items', to='ehr.radiologytests'),
        ),
    ]
