# Generated by Django 5.0.1 on 2024-08-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0024_admission_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthandover',
            name='status',
            field=models.CharField(choices=[('waiting for payment', 'Waiting for Payment'), ('waiting for follow up payment', 'Waiting for Follow Up Payment'), ('waiting for clinic assignment', 'Waiting for Clinic Assignment'), ('waiting for vital signs', 'Waiting for Vital Signs'), ('waiting for consultation', 'Waiting for Consultation'), ('seen', 'Seen'), ('awaiting review', 'Awaiting Review')], max_length=30, null=True),
        ),
    ]
