# Generated by Django 5.0.1 on 2024-12-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0024_alter_radiologyinvestigations_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyinvestigations',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.radiologytest'),
        ),
    ]
