# Generated by Django 5.0.1 on 2024-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0025_remove_patientdata_photo_patientdata_tribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='nok_phone',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='next of kin phone'),
        ),
    ]
