# Generated by Django 5.0.1 on 2024-12-16 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0025_alter_radiologyinvestigations_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologyinvestigations',
            name='payment',
        ),
        migrations.AddField(
            model_name='radiologytests',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_payment', to='ehr.paypoint'),
        ),
    ]
