# Generated by Django 5.0.1 on 2024-08-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0025_alter_patienthandover_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthandover',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
