# Generated by Django 5.0.1 on 2024-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0026_patienthandover_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FileField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
