# Generated by Django 5.0.1 on 2024-12-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0026_remove_radiologyinvestigations_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologyresult',
            name='payment',
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='radiology_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_result', to='ehr.radiologytests'),
        ),
    ]
