# Generated by Django 5.0.1 on 2024-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0027_radiology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiology',
            name='dicom_file',
            field=models.FileField(upload_to='dicom_files/'),
        ),
    ]
