# Generated by Django 5.0.1 on 2024-08-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0027_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_archive', to='ehr.patientdata'),
        ),
    ]
