# Generated by Django 5.0.1 on 2024-08-22 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0028_archive_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='file',
            field=models.FileField(null=True, upload_to='patient_archives/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
