# Generated by Django 5.0.1 on 2024-12-25 21:00

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0028_remove_radiologyresult_radiology_test_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='concurrent_medical_illness',
        ),
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='drug_history',
        ),
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='last_meal',
        ),
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='past_surgical_history',
        ),
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='social_history',
        ),
        migrations.RemoveField(
            model_name='anaesthisiachecklist',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='drughistory',
            name='present_medication',
        ),
        migrations.RemoveField(
            model_name='lastmeal',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='lastmeal',
            name='type',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='qty',
        ),
        migrations.AddField(
            model_name='drughistory',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drughistory',
            name='medication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastmeal',
            name='meal_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lastmeal',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drughistory',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lastmeal',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastsurgicalhistory',
            name='LA_GA',
            field=models.CharField(blank=True, choices=[('LA', 'Local Anaesthesia'), ('GA', 'General Anaesthesia')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastsurgicalhistory',
            name='outcome',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastsurgicalhistory',
            name='surgery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastsurgicalhistory',
            name='when',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastsurgicalhistory',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AnaesthesiaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfussion', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('denctures', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('permanent', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('temporary', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('loose_teeth', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True)),
                ('comment', django_quill.fields.QuillField(blank=True, null=True)),
                ('past_medical_history', django_quill.fields.QuillField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anaesthesia_checklist', to='ehr.patientdata')),
                ('theatre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.theatre')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.ward')),
            ],
        ),
        migrations.AddField(
            model_name='drughistory',
            name='anaesthesia_checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_histories', to='ehr.anaesthesiachecklist'),
        ),
        migrations.AddField(
            model_name='lastmeal',
            name='anaesthesia_checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_meals', to='ehr.anaesthesiachecklist'),
        ),
        migrations.AddField(
            model_name='pastsurgicalhistory',
            name='anaesthesia_checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_surgical_histories', to='ehr.anaesthesiachecklist'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='anaesthesia_checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_histories', to='ehr.anaesthesiachecklist'),
        ),
        migrations.CreateModel(
            name='ConcurrentMedicalIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.CharField(blank=True, max_length=255, null=True)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('anaesthesia_checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concurrent_medical_illnesses', to='ehr.anaesthesiachecklist')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalIllness',
        ),
        migrations.DeleteModel(
            name='AnaesthisiaChecklist',
        ),
    ]
