# Generated by Django 5.0.1 on 2024-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0029_alter_radiology_options_admission_physio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='payment',
        ),
        migrations.AlterField(
            model_name='admission',
            name='ward',
            field=models.CharField(blank=True, choices=[('MALE WARD', 'MALE WARD'), ('FEMALE WARD', 'FEMALE WARD'), ('CHILDRENS WARD', 'CHILDRENS WARD'), ('ICU', 'ICU')], max_length=300, null=True),
        ),
    ]
