# Generated by Django 5.0.1 on 2024-12-26 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0030_rename_loose_teeth_anaesthesiachecklist_lose_teeth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastsurgicalhistory',
            name='anaesthesia_checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_surgical_history', to='ehr.anaesthesiachecklist'),
        ),
    ]
