# Generated by Django 5.0.1 on 2024-05-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0030_remove_admission_payment_alter_admission_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
