# Generated by Django 5.0.1 on 2024-08-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0030_alter_archive_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='clinic',
        ),
    ]
