# Generated by Django 5.0.1 on 2024-08-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0031_remove_patientdata_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic'),
        ),
    ]
