# Generated by Django 5.0.1 on 2024-12-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0031_alter_pastsurgicalhistory_anaesthesia_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardvitalsigns',
            name='height',
            field=models.CharField(blank=True, help_text='cm', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drughistory',
            name='anaesthesia_checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_history', to='ehr.anaesthesiachecklist'),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='anaesthesia_checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_history', to='ehr.anaesthesiachecklist'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_glucose',
            field=models.CharField(blank=True, help_text='mg/dL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_oxygen',
            field=models.CharField(blank=True, help_text='%', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='mmHg', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='body_temperature',
            field=models.CharField(blank=True, help_text='°C', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='height',
            field=models.CharField(blank=True, help_text='cm', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='pulse_rate',
            field=models.CharField(blank=True, help_text='bpm', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='respiration_rate',
            field=models.CharField(blank=True, help_text='breaths/min', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.CharField(blank=True, help_text='kg', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardvitalsigns',
            name='blood_glucose',
            field=models.CharField(blank=True, help_text='mg/dL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardvitalsigns',
            name='blood_oxygen',
            field=models.CharField(blank=True, help_text='%', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardvitalsigns',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='mmHg', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardvitalsigns',
            name='body_temperature',
            field=models.CharField(blank=True, help_text='°C', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardvitalsigns',
            name='pulse_rate',
            field=models.CharField(blank=True, help_text='bpm', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardvitalsigns',
            name='respiration_rate',
            field=models.CharField(blank=True, help_text='breaths/min', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardvitalsigns',
            name='weight',
            field=models.CharField(blank=True, help_text='kg', max_length=10, null=True),
        ),
    ]
