# Generated by Django 5.0.1 on 2024-05-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0031_admission_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='clinic',
        ),
    ]
