# Generated by Django 5.0.1 on 2024-05-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0032_remove_patientdata_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatrenotes',
            name='operated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TheatreBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre', models.CharField(choices=[('MAIN THEATRE', 'MAIN THEATRE'), ('SPINE THEATRE', 'THEATRE')], max_length=30, null=True)),
                ('team', models.CharField(choices=[('WHITE', 'WHITE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_booking', to='ehr.patientdata')),
            ],
        ),
    ]
