# Generated by Django 5.0.1 on 2025-01-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0032_wardvitalsigns_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotest',
            name='description',
        ),
    ]
