# Generated by Django 5.0.1 on 2024-09-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0032_patientdata_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthandover',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
