# Generated by Django 5.0.1 on 2025-01-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0033_remove_physiotest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotest',
            name='category',
            field=models.CharField(choices=[('manual_muscle_strength', 'Manual Muscle Strength Tests'), ('range_of_motion', 'Range of Motion Tests'), ('orthopedic', 'Orthopedic Tests'), ('neurological', 'Neurological Tests'), ('functional_capacity', 'Functional Capacity Tests'), ('pain_assessment', 'Pain Assessment Tests'), ('special_condition', 'Special Condition Tests'), ('rehabilitation_specific', 'Rehabilitation Specific Tests'), ('cardiovascular', 'Cardiovascular Tests'), ('sports_specific', 'Sports-Specific Tests'), ('specialized_orthopedic', 'Specialized Orthopedic Assessments'), ('neurological_specific', 'Neurological Specific Tests'), ('ergonomic_workplace', 'Ergonomic and Workplace Assessments'), ('pediatric', 'Pediatric Physiotherapy Tests'), ('geriatric', 'Geriatric Specific Tests'), ('other', 'Other Tests')], max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='PhysioTestCategory',
        ),
    ]
