# Generated by Django 5.0.1 on 2024-09-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0033_alter_patienthandover_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologyresult',
            name='dicom_file',
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_record', to='ehr.patientdata')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_payment', to='ehr.paypoint')),
                ('record', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='ehr.medicalrecord')),
            ],
            options={
                'verbose_name_plural': 'visit record',
            },
        ),
    ]
