# Generated by Django 5.0.1 on 2024-09-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0034_remove_radiologyresult_dicom_file_visitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='status',
            field=models.CharField(choices=[('waiting for consultation', 'Waiting for Consultation'), ('seen', 'Seen'), ('awaiting review', 'Awaiting Review')], max_length=30, null=True),
        ),
    ]
