# Generated by Django 5.1.6 on 2025-04-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0034_alter_physiotest_category_delete_physiotestcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='means_of_id',
            field=models.CharField(blank=True, choices=[('NIN', 'NIN'), ('Voters Card', 'Voters Card'), ('Drivers Liscence', 'Drivers Liscence'), ('International Passport', 'International Passport')], max_length=200, null=True, verbose_name='Means of Identification'),
        ),
    ]
