# Generated by Django 5.0.1 on 2024-05-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0035_remove_bill_date_remove_bill_total_cost_bill_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery_bill', to='ehr.patientdata'),
        ),
    ]
