# Generated by Django 5.0.1 on 2024-09-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0035_visitrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='nursing_desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.nursingdesk'),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.room'),
        ),
        migrations.DeleteModel(
            name='FollowUpVisit',
        ),
    ]
