# Generated by Django 5.0.1 on 2024-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0036_visitrecord_nursing_desk_visitrecord_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='consultaion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='vitals',
            field=models.BooleanField(default=False),
        ),
    ]
