# Generated by Django 5.1.6 on 2025-05-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0036_appointment_user_visitrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalnote',
            name='appointment',
        ),
    ]
