# Generated by Django 5.0.1 on 2024-05-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0036_alter_bill_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ehr.bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.theatreitem')),
            ],
        ),
    ]
