# Generated by Django 5.0.1 on 2024-05-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0037_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
