# Generated by Django 5.1.6 on 2025-06-10 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0037_remove_clinicalnote_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='lga',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED'), ('DIVORCEE', 'DIVORCEE'), ('WIDOW', 'WIDOW'), ('WIDOWER', 'WIDOWER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nationality',
            field=models.CharField(blank=True, choices=[('NIGERIAN', 'NIGERIAN'), ('NON-CITIZEN', 'NON-CITIZEN')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_phone',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='nok_rel',
            field=models.CharField(blank=True, choices=[('SPOUSE', 'SPOUSE'), ('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('UNCLE', 'UNCLE'), ('AUNT', 'AUNT'), ('NEPHEW', 'NEPHEW'), ('NIECE', 'NIECE'), ('GRANDFATHER', 'GRANDFATHER'), ('GRANDMOTHER', 'GRANDMOTHTER'), ('GRANDSON', 'GRANDSON'), ('GRANDDAUGHTER', 'GRANDAUGHTER'), ('COUSIN', 'COUSIN'), ('FRIEND', 'FRIEND'), ('OTHER', 'OTHER')], max_length=300, null=True, verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='tribe',
            field=models.CharField(blank=True, choices=[('HAUSA', 'Hausa'), ('YORUBA', 'Yoruba'), ('IGBO', 'Igbo'), ('IBIRA', 'Ibira'), ('FULANI', 'Fulani'), ('KANURI', 'Kanuri'), ('IJAW', 'Ijaw'), ('TIV', 'Tiv'), ('NUPE', 'Nupe'), ('EFIK', 'Efik'), ('IDOMA', 'Idoma'), ('IBIBIO', 'Ibibio'), ('IGALA', 'Igala'), ('ANNANG', 'Annang'), ('EBIRA', 'Ebira'), ('JUKUN', 'Jukun'), ('BINI', 'Bini'), ('GWARI', 'Gwari'), ('KURAMA', 'Kurama'), ('ANGAS', 'Angas'), ('BACHAMA', 'Bachama'), ('MBULA', 'Mbula'), ('KAGORO', 'Kagoro'), ('KAMUKU', 'Kamuku'), ('TAROK', 'Tarok'), ('BIROM', 'Birom'), ('BURA', 'Bura'), ('MARGI', 'Margi'), ('SHUA', 'Shua'), ('AWORI', 'Awori'), ('EKITI', 'Ekiti'), ('IJEBU', 'Ijebu'), ('IKALE', 'Ikale'), ('ILORIN', 'Ilorin'), ('ONDO', 'Ondo'), ('OSHOGBO', 'Oshogbo'), ('OYO', 'Oyo'), ('YAGBA', 'Yagba'), ('KABBA', 'Kabba'), ('Other', 'other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='zone',
            field=models.CharField(blank=True, choices=[('NORTH-EAST', 'NORTH-EAST'), ('NORTH-WEST', 'NORTH-WEST'), ('NORTH-CENTRAL', 'NORTH-CENTRAL'), ('SOUTH-EAST', 'SOUTH-EAST'), ('SOUTH-WEST', 'SOUTH-WEST'), ('SOUTH-SOUTH', 'SOUTH-SOUTH')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='physiotest',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.clinic'),
        ),
        migrations.AlterField(
            model_name='visitrecord',
            name='record',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='ehr.medicalrecord'),
        ),
    ]
