# Generated by Django 5.0.1 on 2024-09-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0037_remove_visitrecord_status_visitrecord_consultaion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitrecord',
            old_name='consultaion',
            new_name='consultation',
        ),
    ]
