# Generated by Django 5.1.6 on 2025-06-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0038_alter_patientdata_address_alter_patientdata_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatebilling',
            name='other',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(blank=True, choices=[('new registration', 'new registration'), ('follow up', 'follow up'), ('review', 'review'), ('card replacement', 'card replacement')], max_length=100, null=True),
        ),
    ]
