# Generated by Django 5.0.1 on 2024-05-26 21:07

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0038_alter_patientdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatrenotes',
            name='operation_notes',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
