# Generated by Django 5.0.1 on 2024-09-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0038_rename_consultaion_visitrecord_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='clinic',
        ),
        migrations.DeleteModel(
            name='PatientHandover',
        ),
    ]
