# Generated by Django 5.1.6 on 2025-06-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0039_privatebilling_other_alter_medicalrecord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatebilling',
            name='other',
        ),
        migrations.AddField(
            model_name='privatebilling',
            name='custom_item_name',
            field=models.CharField(blank=True, help_text='Enter custom item name if not in dropdown', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='privatebilling',
            constraint=models.CheckConstraint(condition=models.Q(('item__isnull', False), ('custom_item_name__isnull', False), _negated=True), name='only_one_item_type'),
        ),
    ]
