# Generated by Django 5.0.1 on 2024-09-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0039_remove_patientdata_clinic_delete_patienthandover'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrecord',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitrecord',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehr.team'),
        ),
    ]
