# Generated by Django 5.0.1 on 2024-05-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0039_alter_theatrenotes_operation_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
