# Generated by Django 5.0.1 on 2024-05-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0040_dicomfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='followupvisit',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patienthandover',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='theatrebooking',
            name='theatre',
            field=models.CharField(choices=[('MAIN THEATRE', 'MAIN THEATRE'), ('SPINE THEATRE', 'SPINE THEATRE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='clinic',
            field=models.CharField(choices=[('A & E', 'A & E'), ('SOPD', 'SOPD')], max_length=30, null=True),
        ),
    ]
