# Generated by Django 5.1.6 on 2025-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0040_remove_privatebilling_other_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(blank=True, choices=[('new registration', 'new registration'), ('follow up', 'follow up'), ('review', 'review'), ('dressing', 'dressing'), ('card replacement', 'card replacement')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('FAMILY', 'FAMILY')], max_length=10, null=True),
        ),
    ]
