# Generated by Django 5.0.1 on 2024-06-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0041_alter_appointment_clinic_alter_followupvisit_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
