# Generated by Django 5.1.6 on 2025-06-26 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0041_alter_appointment_options_alter_medicalrecord_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wardmedication',
            options={'verbose_name_plural': 'ward medications'},
        ),
        migrations.AlterField(
            model_name='wardmedication',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wardmedication',
            name='drug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='PatientDispensedDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('total_dispensed', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('dispensed_date', models.DateTimeField()),
                ('dispensed_by', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_drugs_stock', to='ehr.patientdata')),
            ],
            options={
                'verbose_name_plural': 'Patient Dispensed Drugs',
            },
        ),
        migrations.CreateModel(
            name='WardMedicationDispensed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_administered', models.PositiveIntegerField(verbose_name='Quantity Given')),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dispensed_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='ehr.patientdispenseddrug')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_medication_dispensed', to='ehr.patientdata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ward Medications (Dispensed)',
            },
        ),
    ]
