# Generated by Django 5.1.6 on 2025-06-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0042_alter_wardmedication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardmedicationdispensed',
            name='dose_administered',
            field=models.PositiveIntegerField(verbose_name='Qty Given'),
        ),
    ]
