# Generated by Django 5.0.1 on 2024-06-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0043_radiologytest_radiologyresult_delete_radiology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physio',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physio_payment', to='ehr.paypoint'),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_results', to='ehr.patientdata'),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_result_payment', to='ehr.paypoint'),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='test',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ehr.radiologytest'),
        ),
    ]
