# Generated by Django 5.1.6 on 2025-06-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0043_alter_wardmedicationdispensed_dose_administered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdispenseddrug',
            options={'ordering': ['-dispensed_date']},
        ),
        migrations.AlterModelOptions(
            name='wardmedicationdispensed',
            options={'ordering': ['-updated'], 'verbose_name_plural': 'Ward Medications (Dispensed)'},
        ),
        migrations.AlterField(
            model_name='patientdispenseddrug',
            name='dispensed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientdispenseddrug',
            name='remaining_quantity',
            field=models.PositiveIntegerField(verbose_name='Remaining Quantity'),
        ),
        migrations.AlterField(
            model_name='patientdispenseddrug',
            name='total_dispensed',
            field=models.PositiveIntegerField(verbose_name='Total Dispensed'),
        ),
        migrations.AlterField(
            model_name='wardmedicationdispensed',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
