# Generated by Django 5.0.1 on 2024-06-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0044_alter_physio_payment_alter_radiologyresult_patient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
